name: CI - Test Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Flask App Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Debug File Listing
        run: ls -la

      - name: Install Dependencies
        working-directory: model
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Copy Model File
        run: cp calibrated_rf_model.joblib model/

      - name: Run Tests
        run: |
          pip install pytest
          PYTHONPATH=./model pytest model/tests/
