name: CI - Test Flask App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Flask App Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r model/requirements.txt

      - name: Run Linter (Flake8)
        run: |
          pip install flake8
          flake8 model/app.py --ignore=E501

      - name: Run Tests
        run: |
          pip install pytest
          pytest model/tests/
